# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 傲雪の
subtitle: Kent's blog
description: 无聊的一天搭配神经的我～
keywords: Kentural,傲雪の
author: Kentural
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://b.oxue.de
permalink: p/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

giscus:
  enable: true
  repo: xxytan/xxytan # Github repository name
  repo_id: R_kgDOQr23UA # Github repository id
  category: Announcements # Github discussion category
  category_id: DIC_kwDOQr23UM4C0BTd # Github discussion category id
  # Available values: pathname | url | title | og:title
  mapping: pathname
  # Available values: 0 | 1
  reactions_enabled: 1
   # Available values: 0 | 1
  emit_metadata: 1
  # Available values: light | light_high_contrast | light_protanopia | light_tritanopia | dark | dark_high_contrast | dark_protanopia | dark_tritanopia | dark_dimmed | preferred_color_scheme | transparent_dark | noborder_light | noborder_dark | noborder_gray | cobalt | purple_dark
  theme: preferred_color_scheme
  # Available values: en | zh-CN
  lang: zh-CN
  # Place the comment box above the comments
  input_position: top
  # Load the comments lazily
  loading: lazy

fireworks:
  enable: true

# Change title and favicon when window is hidden and visible.
title_change:
  enable: true
  # Enabling this feature on non-desktop devices may not be a good choice, but it depends on you.
  onmobile: true
  # Enable random title or not.
  # Basically `random: true` means you have several titles to display and `random: false` means you have only one title to display.
  # When `random: true`, YOU MUST FOLLOW the format which has been commented in two title options below.
  # When `random: false`, please fill in the same line of the title option, like `title: one title`.
  random: false
  # Restore the original title after the specified time in milliseconds.
  timeout: 2019
  # Options when window is hidden.
  hidden:
    favicon: /self/favicon.ico
    title: 404 *-*
      #- 404
      #- φ(*￣0￣)
      #- Waiting for you.
  # Options when window is visible.
  visible:
    favicon: /self/favicon.ico
    title: Just a joke >~<
      #- 200
      #- (✿◡‿◡)
      #- Welcome back!

subtitle_typing:
  enable: true
  typing_speed: 100
  deleting_speed: 50
  pause_before_delete: 2000
  pause_before_type: 500
  subtitles:
    - 无聊的一天搭配神经的我～
    - Day bores me but I'm crazy~
    - 正在吃吃吃…
    - Still enjoying…

aplayer:
  meting: true                                  # MetingJS 支持
  meting_api: https://meting.roc.us.ci/api             # 自定义 Meting API

markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: false
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
    - markdown-it-footnote
    - markdown-it-mark
    - markdown-it-emoji
    - markdown-it-attrs
    - markdown-it-container
    - markdown-it-task-lists
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
  images:
    lazyload: false
    prepend_root: false
    post_asset: false
  inline: false  # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline

